"""Rebuild graphify-out/wiki/ and regroup its index.

    python graphify-out/refresh_wiki.py        # from the repo root

`graphify export wiki` writes one flat, size-sorted index and clears every .md
in wiki/ as it goes, so the grouped map has to be re-applied afterwards — that
is the only reason this script exists. Run it when the wiki looks stale; the
post-commit hook refreshes graph.json but never the wiki.
"""
import json
import re
import subprocess
import sys
from collections import Counter, defaultdict
from pathlib import Path
from urllib.parse import quote

OUT = Path('graphify-out')

# ---- 1. regenerate the articles -------------------------------------------
# .graphify_python is machine-specific and gitignored, so it is absent on a
# fresh clone — fall back to whatever interpreter is running this script.
_pin = OUT / '.graphify_python'
py = _pin.read_text(encoding='utf-8').strip() if _pin.exists() else sys.executable
r = subprocess.run([py, '-m', 'graphify', 'export', 'wiki'],
                   capture_output=True, text=True, encoding='utf-8', errors='replace')
print((r.stdout or '').strip() or (r.stderr or '').strip())
if r.returncode != 0:
    sys.exit(r.returncode)

# ---- 2. rewrite the index with a grouped map on top -----------------------
g = json.loads((OUT / 'graph.json').read_text(encoding='utf-8'))
labels = json.loads((OUT / '.graphify_labels.json').read_text(encoding='utf-8'))


def slug(label: str) -> str:
    """Mirror graphify.export._safe_filename, then URL-quote for the link."""
    return quote(re.sub(r'[<>:"/\\|?*]', '-', label).replace(' ', '_')) + '.md'


def bucket(top: str) -> str:
    top = top.replace('\\', '/')
    if 'lightweight-charts' in top:                          return 'Vendor chart library'
    if top.startswith('app/engine/'):                        return 'Engines'
    if top.startswith('app/tests/') and top.endswith('.js'): return 'JS suites (static-text contracts)'
    if top.startswith('app/tests/'):                         return 'Python suites'
    if top.startswith('app/static/assets/'):                 return 'Branding'
    if top.startswith('app/static/'):                        return 'UI (browser)'
    if top.endswith(('.md', '.txt', '.yml', '.mjs', '.json')): return 'Docs, conventions & config'
    if top.startswith('app/'):                               return 'App runtime & server'
    return 'Other'


by_c = defaultdict(list)
for n in g['nodes']:
    by_c[n['community']].append(n)

groups = defaultdict(list)
for cid, nodes in by_c.items():
    top = Counter((x.get('source_file') or '?') for x in nodes).most_common(1)[0][0]
    groups[bucket(top)].append((labels.get(str(cid), f'Community {cid}'),
                                len(nodes), top.replace('\\', '/')))

ORDER = ['Engines', 'App runtime & server', 'UI (browser)', 'Docs, conventions & config',
         'Python suites', 'JS suites (static-text contracts)', 'Vendor chart library',
         'Branding', 'Other']

# Stamp the commit the graph was built from. A sha alone rots — anyone reading
# this later has to compare it against HEAD themselves, so say so explicitly.
# The hard warning fires only when the graph was ALREADY behind on real code at
# build time; a docs-only commit moves HEAD without invalidating anything here.
CODE_EXT = ('.py', '.js', '.mjs', '.ts', '.html', '.css')
built_full = g.get('built_at_commit') or ''
built = built_full[:12] or 'unknown'
drifted = []
if built_full:
    _d = subprocess.run(['git', 'diff', '--name-only', f'{built_full}..HEAD'],
                        capture_output=True, text=True)
    if _d.returncode == 0:
        drifted = [f for f in _d.stdout.split()
                   if f.endswith(CODE_EXT) and not f.startswith('graphify-out/')]

if drifted:
    stamp = (f'> **Stale — built from `{built}`, and {len(drifted)} code file(s) have changed '
             f'since.** Run `graphify update .`, then `python graphify-out/refresh_wiki.py`.')
else:
    stamp = (f'> Built from commit `{built}`. If `git rev-parse --short HEAD` differs and code '
             f'has changed since, re-run `python graphify-out/refresh_wiki.py`.')

lines = ['# Knowledge Graph Index', '',
         '> Generated by `graphify export wiki`, then grouped by `refresh_wiki.py`.',
         '> Read a group heading, then the article. The flat size-sorted list is at the bottom.',
         '', stamp, '',
         '> Communities here are file-shaped: 92% of the edges in this graph stay inside one',
         '> file, so clustering had little to group by except which file a symbol lives in.',
         '> Good for "where does X live and what is near it". Not a map of a flow across files.',
         '',
         f"**{len(g['nodes'])} nodes · {len(g['links'])} edges · {len(by_c)} communities**", '',
         '---', '', '## Start here', '']

for grp in ORDER:
    if grp not in groups:
        continue
    items = sorted(groups[grp], key=lambda t: -t[1])
    lines.append(f'### {grp} — {len(items)} articles, {sum(i[1] for i in items)} nodes')
    lines.append('')
    if grp == 'Vendor chart library':
        lines.append('_Minified third-party `lightweight-charts.js`. Not project code — '
                     'skip unless debugging the chart._')
        lines.append('')
    for label, n, top in items:
        lines.append(f'- [{label}]({slug(label)}) — {n} nodes · `{top}`')
    lines.append('')

lines += ['---', '']

idx = OUT / 'wiki' / 'index.md'
body = idx.read_text(encoding='utf-8')
cut = body.find('## Communities')          # keep graphify's own flat catalog below
idx.write_text('\n'.join(lines) + (body[cut:] if cut != -1 else body), encoding='utf-8')

print(f'index.md regrouped: {sum(len(v) for v in groups.values())} articles in {len(groups)} groups')
